"""Top-level conversion: HF model_id (or local config.json) -> n-orca."""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from n_orca.ast import Architecture
from n_orca.compiler import compile_mermaid
from n_orca.hf.adapters import get_adapter, list_adapters
from n_orca.hf.client import HfClient
from n_orca.render import render
from n_orca.verifier import verify, VerificationReport


class UnsupportedModelError(Exception):
    pass


@dataclass
class ConversionResult:
    architecture: Architecture
    markdown: str
    mermaid: str
    report: VerificationReport
    model_id: str | None = None
    revision: str | None = None

    def write_markdown(self, path: str | Path) -> Path:
        p = Path(path)
        p.write_text(self.markdown, encoding="utf-8")
        return p

    def write_mermaid(self, path: str | Path) -> Path:
        p = Path(path)
        p.write_text(self.mermaid, encoding="utf-8")
        return p


def convert(
    source: str | dict[str, Any] | Path,
    *,
    revision: str | None = None,
    name: str | None = None,
    client: HfClient | None = None,
) -> ConversionResult:
    """Convert an HF model or config dict to an n-orca architecture.

    `source` may be:
    - an HF model_id string (e.g. "gpt2", "meta-llama/Llama-2-7b-hf")
    - a path to a local `config.json`
    - an already-loaded `dict` config

    Returns a `ConversionResult` carrying the AST, rendered markdown,
    Mermaid diagram, and verification report.
    """
    config, model_id, revision = _load_config(source, revision=revision, client=client)

    adapter = get_adapter(config)
    if adapter is None:
        supported = ", ".join(
            sorted({k for a in list_adapters() for k in a.model_types})
        )
        raise UnsupportedModelError(
            f"no adapter registered for model_type={config.get('model_type')!r} /"
            f" architectures={config.get('architectures')!r}."
            f" Supported model types: {supported}"
        )

    arch = adapter.build(config, name=name)
    # Stamp provenance so the runtime-capability backend has the authoritative
    # model_type (not a name/description guess). Round-trips as `## runtime`.
    mt = config.get("model_type")
    if mt and "model_type" not in arch.metadata:
        arch.metadata["model_type"] = str(mt)
    report = verify(arch)
    markdown = render(arch)
    mermaid = compile_mermaid(arch)

    # Embed provenance into the markdown description if not already present.
    if model_id and "Generated by" in (arch.description or ""):
        arch.description = (
            (arch.description or "")
            + f" Source: `{model_id}`"
            + (f" @ {revision}" if revision else "")
        )
        markdown = render(arch)

    return ConversionResult(
        architecture=arch,
        markdown=markdown,
        mermaid=mermaid,
        report=report,
        model_id=model_id,
        revision=revision,
    )


def _load_config(
    source: str | dict[str, Any] | Path,
    *,
    revision: str | None,
    client: HfClient | None,
) -> tuple[dict[str, Any], str | None, str | None]:
    """Resolve `source` to a config dict and (optional) provenance."""
    if isinstance(source, dict):
        return source, None, revision

    if isinstance(source, Path) or (isinstance(source, str) and _looks_like_path(source)):
        path = Path(source)
        if path.is_file():
            with path.open("r", encoding="utf-8") as fh:
                return json.load(fh), str(path), revision

    # Treat as HF model_id.
    if not isinstance(source, str):
        raise UnsupportedModelError(f"cannot resolve source: {source!r}")
    cli = client or HfClient()
    config = cli.download_config(source, revision=revision)
    return config, source, revision


def _looks_like_path(s: str) -> bool:
    return s.endswith(".json") or "/" in s and Path(s).exists()
