"""BERT / DistilBERT / RoBERTa family adapter.

Encoder-only transformer with token + positional embeddings (segment
embeddings are omitted in v1 — they require a second integer input that
n-orca v0 doesn't yet model). Each block is post-norm.
"""
from __future__ import annotations

from typing import Any

from n_orca.ast import (
    Architecture,
    Hyperparameter,
    Tensor,
    Layer,
    FlowEdge,
    OpCall,
    Invariant,
)
from n_orca.hf.adapters.base import HfAdapter, register
from n_orca.hf.adapters._blocks import post_norm_encoder_block


class BertAdapter(HfAdapter):
    model_types = ("bert", "roberta", "distilbert", "electra", "albert")

    def build(self, config: dict[str, Any], *, name: str | None = None) -> Architecture:
        family = (config.get("model_type") or "bert").lower()
        vocab = int(config.get("vocab_size", 30522))
        d_model = int(config.get("hidden_size", 768))
        n_layer = int(config.get("num_hidden_layers", 12))
        n_head = int(config.get("num_attention_heads", 12))
        d_ff = int(config.get("intermediate_size", 3072))
        max_pos = int(config.get("max_position_embeddings", 512))
        dropout = float(config.get("hidden_dropout_prob", 0.1))

        arch = Architecture(
            name=name or _derive_name(family, config, d_model, n_layer),
            description=(
                f"{family.upper()} encoder-only transformer."
                f" Token + learned positional embeddings, {n_layer} post-norm blocks."
                " Segment-type embeddings are omitted in this generated form."
                " Generated by `n-orca hf convert` from a Hugging Face config."
            ),
            hyperparameters=[
                Hyperparameter("vocab_size", "int", vocab),
                Hyperparameter("d_model", "int", d_model),
                Hyperparameter("n_layer", "int", n_layer),
                Hyperparameter("n_heads", "int", n_head),
                Hyperparameter("d_ff", "int", d_ff),
                Hyperparameter("max_pos", "int", max_pos),
                Hyperparameter("dropout", "float", dropout),
            ],
            tensors=[
                Tensor("input_ids", ("B", "S"), "int64"),
                Tensor("last_hidden", ("B", "S", "d_model"), "float32"),
            ],
        )

        arch.layers.append(Layer(name="input_ids", is_input=True,
                                 description="Token IDs"))
        arch.layers.append(Layer(name="tok_embed",
                                 op=OpCall("Embedding", ["vocab_size", "d_model"])))
        arch.layers.append(Layer(name="pos_embed",
                                 description="Learned absolute positional embeddings",
                                 op=OpCall("PositionalEmbedding", ["max_pos", "d_model"])))
        arch.layers.append(Layer(name="emb_ln",
                                 description="LayerNorm applied to the embedding sum",
                                 op=OpCall("LayerNorm", ["d_model"])))
        arch.layers.append(Layer(name="emb_drop",
                                 op=OpCall("Dropout", ["dropout"])))
        arch.flow.extend([
            FlowEdge("input_ids", "tok_embed", "tokens"),
            FlowEdge("tok_embed", "pos_embed", "te"),
            FlowEdge("pos_embed", "emb_ln", "pe"),
            FlowEdge("emb_ln", "emb_drop", "e"),
        ])

        prev = "emb_drop"
        for i in range(n_layer):
            layers, edges, prev = post_norm_encoder_block(
                index=i,
                prev_layer=prev,
                d_model="d_model", n_heads="n_heads",
                d_ff="d_ff", dropout="dropout",
            )
            arch.layers.extend(layers)
            arch.flow.extend(edges)

        arch.layers.append(Layer(name="last_hidden", is_output=True,
                                 description="Final encoder hidden states"))
        arch.flow.append(FlowEdge(prev, "last_hidden", "last_hidden"))

        arch.invariants.append(Invariant("output_shape", "=", ("B", "S", "d_model")))
        return arch


def _derive_name(family: str, config: dict[str, Any], d_model: int, n_layer: int) -> str:
    name_id = config.get("_name_or_path") or config.get("name_or_path") or ""
    if name_id:
        bare = name_id.split("/")[-1].replace("-", "_").replace(".", "_")
        return _Pascal(bare)
    return f"{_Pascal(family)}_{n_layer}L_{d_model}d"


def _Pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_") if p) or "Model"


register(BertAdapter())