"""ESM-2 family adapter.

ESM-2 is a protein language model: a BERT-style transformer encoder trained
on UniRef50 / UniRef90. Structurally it is very close to BERT:

- Encoder-only, ~33-symbol vocabulary (20 amino acids + special tokens)
- N pre-norm transformer blocks
- Rotary positional embeddings (RoPE) on Q/K — *not* learned absolute pos
  embeddings as in BERT. We approximate this in n-orca v1 by omitting the
  positional-embedding layer entirely; the topology is otherwise identical.
- Final LayerNorm at the encoder head (pre-norm convention)

This adapter handles facebook/esm2_t6_8M_UR50D, esm2_t12_35M_UR50D,
esm2_t30_150M_UR50D, esm2_t33_650M_UR50D, esm2_t36_3B_UR50D, and
esm2_t48_15B_UR50D.
"""
from __future__ import annotations

from typing import Any

from n_orca.ast import (
    Architecture,
    Hyperparameter,
    Tensor,
    Layer,
    FlowEdge,
    OpCall,
    Invariant,
)
from n_orca.hf.adapters.base import HfAdapter, register
from n_orca.hf.adapters._blocks import pre_norm_decoder_block


class EsmAdapter(HfAdapter):
    """ESM-2 encoder. Structurally pre-norm with rotary positions (approximated)."""

    model_types = ("esm",)

    def build(self, config: dict[str, Any], *, name: str | None = None) -> Architecture:
        vocab = int(config.get("vocab_size", 33))
        d_model = int(config.get("hidden_size", 320))
        n_layer = int(config.get("num_hidden_layers", 6))
        n_head = int(config.get("num_attention_heads", 20))
        d_ff = int(config.get("intermediate_size", 1280))
        max_pos = int(config.get("max_position_embeddings", 1026))
        dropout = float(config.get("hidden_dropout_prob", 0.0))

        arch = Architecture(
            name=name or _derive_name("esm2", config, d_model, n_layer),
            description=(
                "ESM-2 protein language model — encoder-only transformer."
                f" {n_layer} pre-norm blocks with rotary positional embeddings"
                " (RoPE is applied inside attention; n-orca v1 represents"
                " attention as a plain MultiHeadAttention, so the positional"
                " mechanism is left implicit)."
                " Generated by `n-orca hf convert` from a Hugging Face config."
            ),
            hyperparameters=[
                Hyperparameter("vocab_size", "int", vocab),
                Hyperparameter("d_model", "int", d_model),
                Hyperparameter("n_layer", "int", n_layer),
                Hyperparameter("n_heads", "int", n_head),
                Hyperparameter("d_ff", "int", d_ff),
                Hyperparameter("max_pos", "int", max_pos),
                Hyperparameter("dropout", "float", dropout),
            ],
            tensors=[
                Tensor("input_ids", ("B", "S"), "int64"),
                Tensor("last_hidden", ("B", "S", "d_model"), "float32"),
            ],
        )

        arch.layers.append(Layer(
            name="input_ids", is_input=True,
            description="Tokenized protein sequence (20 amino acids + specials)",
        ))
        arch.layers.append(Layer(
            name="tok_embed",
            description="Amino-acid token embeddings (rotary positions added inside attention)",
            op=OpCall("Embedding", ["vocab_size", "d_model"]),
        ))
        arch.flow.append(FlowEdge("input_ids", "tok_embed", "tokens"))

        prev = "tok_embed"
        for i in range(n_layer):
            layers, edges, prev = pre_norm_decoder_block(
                index=i,
                prev_layer=prev,
                d_model="d_model", n_heads="n_heads",
                d_ff="d_ff", dropout="dropout",
            )
            arch.layers.extend(layers)
            arch.flow.extend(edges)

        arch.layers.append(Layer(
            name="final_ln",
            description="Final pre-norm LayerNorm",
            op=OpCall("LayerNorm", ["d_model"]),
        ))
        arch.layers.append(Layer(
            name="last_hidden", is_output=True,
            description="Per-residue contextualised embeddings"
                        " — the SAE training target for protein interpretability",
        ))
        arch.flow.extend([
            FlowEdge(prev, "final_ln", "y"),
            FlowEdge("final_ln", "last_hidden", "last_hidden"),
        ])

        arch.invariants.append(Invariant("output_shape", "=", ("B", "S", "d_model")))
        return arch


def _derive_name(family: str, config: dict[str, Any], d_model: int, n_layer: int) -> str:
    name_id = config.get("_name_or_path") or config.get("name_or_path") or ""
    if name_id:
        bare = name_id.split("/")[-1].replace("-", "_").replace(".", "_")
        return _Pascal(bare)
    return f"Esm2_{n_layer}L_{d_model}d"


def _Pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_") if p) or "Model"


register(EsmAdapter())
