"""GPT-2 family adapter: decoder-only, pre-LN, learned positional embeddings."""
from __future__ import annotations

from typing import Any

from n_orca.ast import (
    Architecture,
    Hyperparameter,
    Tensor,
    Layer,
    FlowEdge,
    OpCall,
    Invariant,
)
from n_orca.hf.adapters.base import HfAdapter, register
from n_orca.hf.adapters._blocks import pre_norm_decoder_block


class Gpt2Adapter(HfAdapter):
    model_types = ("gpt2", "gpt_neo", "gpt_neox", "openai-gpt")

    def build(self, config: dict[str, Any], *, name: str | None = None) -> Architecture:
        vocab = int(config.get("vocab_size", 50257))
        d_model = int(config.get("n_embd") or config.get("hidden_size") or 768)
        n_layer = int(config.get("n_layer") or config.get("num_hidden_layers") or 12)
        n_head = int(config.get("n_head") or config.get("num_attention_heads") or 12)
        d_ff = int(
            config.get("n_inner")
            or config.get("intermediate_size")
            or 4 * d_model
        )
        max_pos = int(
            config.get("n_positions") or config.get("max_position_embeddings") or 1024
        )
        dropout = float(
            config.get("attn_pdrop")
            or config.get("resid_pdrop")
            or config.get("hidden_dropout_prob")
            or 0.1
        )

        arch = Architecture(
            name=name or _derive_name("gpt2", config, d_model, n_layer),
            description=(
                "Decoder-only transformer with learned token + positional embeddings,"
                f" {n_layer} pre-norm blocks, and a tied language-modeling head."
                " Generated by `n-orca hf convert` from a Hugging Face config."
            ),
            hyperparameters=[
                Hyperparameter("vocab_size", "int", vocab),
                Hyperparameter("d_model", "int", d_model),
                Hyperparameter("n_layer", "int", n_layer),
                Hyperparameter("n_heads", "int", n_head),
                Hyperparameter("d_ff", "int", d_ff),
                Hyperparameter("max_pos", "int", max_pos),
                Hyperparameter("dropout", "float", dropout),
            ],
            tensors=[
                Tensor("input_ids", ("B", "S"), "int64"),
                Tensor("logits", ("B", "S", "vocab_size"), "float32"),
            ],
        )

        # Input + embedding stem.
        arch.layers.append(Layer(name="input_ids", is_input=True,
                                 description="Token IDs"))
        arch.layers.append(Layer(name="tok_embed",
                                 op=OpCall("Embedding", ["vocab_size", "d_model"])))
        arch.layers.append(Layer(name="pos_embed",
                                 description="Learned absolute positional embeddings",
                                 op=OpCall("PositionalEmbedding", ["max_pos", "d_model"])))
        arch.layers.append(Layer(name="drop_emb",
                                 op=OpCall("Dropout", ["dropout"])))
        arch.flow.extend([
            FlowEdge("input_ids", "tok_embed", "tokens"),
            FlowEdge("tok_embed", "pos_embed", "te"),
            FlowEdge("pos_embed", "drop_emb", "pe"),
        ])

        prev = "drop_emb"
        for i in range(n_layer):
            layers, edges, prev = pre_norm_decoder_block(
                index=i,
                prev_layer=prev,
                d_model="d_model", n_heads="n_heads",
                d_ff="d_ff", dropout="dropout",
            )
            arch.layers.extend(layers)
            arch.flow.extend(edges)

        # Final LN, LM head, output.
        arch.layers.append(Layer(name="final_ln",
                                 op=OpCall("LayerNorm", ["d_model"])))
        arch.layers.append(Layer(name="lm_head",
                                 op=OpCall("Linear", ["d_model", "vocab_size"])))
        arch.layers.append(Layer(name="logits", is_output=True,
                                 description="Per-position logits"))
        arch.flow.extend([
            FlowEdge(prev, "final_ln", "y"),
            FlowEdge("final_ln", "lm_head", "y_n"),
            FlowEdge("lm_head", "logits", "logits"),
        ])

        arch.invariants.append(Invariant("output_shape", "=", ("B", "S", "vocab_size")))
        return arch


def _derive_name(family: str, config: dict[str, Any], d_model: int, n_layer: int) -> str:
    name_id = config.get("_name_or_path") or config.get("name_or_path") or ""
    if name_id:
        bare = name_id.split("/")[-1].replace("-", "_").replace(".", "_")
        return _Pascal(bare)
    return f"{_Pascal(family)}_{n_layer}L_{d_model}d"


def _Pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_") if p) or "Model"


register(Gpt2Adapter())
