"""LLaMA / Mistral / Qwen / Gemma family adapter.

These all share the same skeleton: pre-norm decoder blocks with RMSNorm,
attention with rotary position embeddings, and a SwiGLU feed-forward. In
v1 of n-orca, RMSNorm and SwiGLU are approximated by LayerNorm and
FeedForward (the structural verifier still catches all topology bugs).
"""
from __future__ import annotations

from typing import Any

from n_orca.ast import (
    Architecture,
    Hyperparameter,
    Tensor,
    Layer,
    FlowEdge,
    OpCall,
    Invariant,
)
from n_orca.hf.adapters.base import HfAdapter, register
from n_orca.hf.adapters._blocks import pre_norm_decoder_block


class LlamaFamilyAdapter(HfAdapter):
    model_types = (
        "llama", "mistral", "mixtral",
        "qwen2", "qwen3", "qwen2_moe",
        "gemma", "gemma2",
        "phi", "phi3",
    )

    def build(self, config: dict[str, Any], *, name: str | None = None) -> Architecture:
        family = (config.get("model_type") or "llama").lower()
        vocab = int(config.get("vocab_size", 32000))
        d_model = int(config.get("hidden_size", 4096))
        n_layer = int(config.get("num_hidden_layers", 32))
        n_head = int(config.get("num_attention_heads", 32))
        d_ff = int(config.get("intermediate_size", 11008))
        max_pos = int(config.get("max_position_embeddings", 4096))

        arch = Architecture(
            name=name or _derive_name(family, config, d_model, n_layer),
            description=(
                f"{family.title()}-family decoder-only transformer."
                f" {n_layer} pre-norm blocks with RMSNorm (approximated as LayerNorm),"
                " rotary attention, and SwiGLU feed-forward (approximated as FeedForward)."
                " Generated by `n-orca hf convert` from a Hugging Face config."
            ),
            hyperparameters=[
                Hyperparameter("vocab_size", "int", vocab),
                Hyperparameter("d_model", "int", d_model),
                Hyperparameter("n_layer", "int", n_layer),
                Hyperparameter("n_heads", "int", n_head),
                Hyperparameter("d_ff", "int", d_ff),
                Hyperparameter("max_pos", "int", max_pos),
                Hyperparameter("dropout", "float", 0.0),
            ],
            tensors=[
                Tensor("input_ids", ("B", "S"), "int64"),
                Tensor("logits", ("B", "S", "vocab_size"), "float32"),
            ],
        )

        arch.layers.append(Layer(name="input_ids", is_input=True,
                                 description="Token IDs"))
        arch.layers.append(Layer(name="tok_embed",
                                 description="Token embeddings (rotary positions applied inside attention)",
                                 op=OpCall("Embedding", ["vocab_size", "d_model"])))
        arch.flow.append(FlowEdge("input_ids", "tok_embed", "tokens"))

        prev = "tok_embed"
        for i in range(n_layer):
            layers, edges, prev = pre_norm_decoder_block(
                index=i,
                prev_layer=prev,
                d_model="d_model", n_heads="n_heads",
                d_ff="d_ff", dropout="dropout",
            )
            arch.layers.extend(layers)
            arch.flow.extend(edges)

        arch.layers.append(Layer(name="final_norm",
                                 description="Final RMSNorm",
                                 op=OpCall("LayerNorm", ["d_model"])))
        arch.layers.append(Layer(name="lm_head",
                                 op=OpCall("Linear", ["d_model", "vocab_size"])))
        arch.layers.append(Layer(name="logits", is_output=True))
        arch.flow.extend([
            FlowEdge(prev, "final_norm", "y"),
            FlowEdge("final_norm", "lm_head", "y_n"),
            FlowEdge("lm_head", "logits", "logits"),
        ])

        arch.invariants.append(Invariant("output_shape", "=", ("B", "S", "vocab_size")))
        return arch


def _derive_name(family: str, config: dict[str, Any], d_model: int, n_layer: int) -> str:
    name_id = config.get("_name_or_path") or config.get("name_or_path") or ""
    if name_id:
        bare = name_id.split("/")[-1].replace("-", "_").replace(".", "_")
        return _Pascal(bare)
    return f"{_Pascal(family)}_{n_layer}L_{d_model}d"


def _Pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_") if p) or "Model"


register(LlamaFamilyAdapter())
