"""PyTorch compiler.

Emits a single `nn.Module` subclass whose `__init__` instantiates each layer
that needs parameters, and whose `forward()` threads tensors through the DAG
in topological order following the flow table.

Hyperparameters become `__init__` arguments with declared defaults.
"""
from __future__ import annotations

from n_orca.ast import Architecture
from n_orca.ops import get_op, UnknownOpError


def compile_pytorch(arch: Architecture) -> str:
    """Compile `arch` to a self-contained Python module string."""
    lines: list[str] = []
    lines.append('"""Auto-generated by n-orca. Do not edit by hand."""')
    lines.append("import torch")
    lines.append("from torch import nn")
    lines.append("")
    lines.append("")
    lines.append(f"class {_class_name(arch.name)}(nn.Module):")

    # __init__
    init_args = ["self"]
    for hp in arch.hyperparameters:
        default = _default_literal(hp)
        init_args.append(f"{hp.name}={default}" if default is not None else hp.name)
    lines.append(f"    def __init__({', '.join(init_args)}):")
    lines.append("        super().__init__()")

    for hp in arch.hyperparameters:
        lines.append(f"        self.{hp.name} = {hp.name}")

    module_emitted = False
    for ly in arch.layers:
        if ly.is_input or ly.is_output or ly.op is None:
            continue
        try:
            spec = get_op(ly.op.name)
        except UnknownOpError:
            lines.append(
                f"        # TODO: replace with a real {ly.op.name!r} module"
            )
            lines.append(f"        self.{_pyid(ly.name)} = nn.Identity()")
            module_emitted = True
            continue
        if not spec.is_module:
            continue
        init_rhs = spec.pytorch_init(ly.op.args)
        lines.append(f"        self.{_pyid(ly.name)} = {init_rhs}")
        module_emitted = True

    if not module_emitted and not arch.hyperparameters:
        lines.append("        pass")

    lines.append("")

    # forward()
    inputs = [ly.name for ly in arch.inputs()]
    fwd_args = ["self"] + [_pyid(n) for n in inputs]
    lines.append(f"    def forward({', '.join(fwd_args)}):")

    succ: dict[str, list[str]] = {ly.name: [] for ly in arch.layers}
    pred: dict[str, list[str]] = {ly.name: [] for ly in arch.layers}
    for e in arch.flow:
        succ[e.source].append(e.target)
        pred[e.target].append(e.source)

    indeg = {n: len(pred[n]) for n in pred}
    queue = [n for n, d in indeg.items() if d == 0]
    topo: list[str] = []
    while queue:
        n = queue.pop(0)
        topo.append(n)
        for m in succ[n]:
            indeg[m] -= 1
            if indeg[m] == 0:
                queue.append(m)

    # Map: layer name -> Python variable holding its output tensor.
    var: dict[str, str] = {n: _pyid(n) for n in inputs}
    has_body = False

    # Ops that return (attn_output, attn_weights) tuple and need special LHS unpack
    # for correct emission (bypass the generic module path).
    ATTN_TUPLE_OPS = {"MultiHeadAttention", "DualStreamJointAttention"}

    for n in topo:
        ly = arch.layer(n)
        if ly is None or ly.is_input:
            continue
        input_vars = [var[p] for p in [e.source for e in arch.flow if e.target == n]]

        if ly.is_output:
            if len(input_vars) == 1:
                var[n] = input_vars[0]
            elif input_vars:
                var[n] = input_vars[0]
            continue

        if ly.op is None:
            continue

        try:
            spec = get_op(ly.op.name)
        except UnknownOpError:
            out_var = _pyid(n)
            lines.append(
                f"        {out_var}_out = self.{_pyid(n)}({input_vars[0]})"
            )
            var[n] = f"{out_var}_out"
            has_body = True
            continue

        out_var = _pyid(n) + "_out"

        if ly.op.name in ATTN_TUPLE_OPS:
            x = input_vars[0]
            lines.append(
                f"        {out_var}, _ = self.{_pyid(n)}({x}, {x}, {x})"
            )
        elif spec.is_module:
            # Some module ops use a {NAME} template in their call emitter
            # (e.g. PositionalEmbedding needs the attribute name inline).
            call = spec.pytorch_call(ly.op.args, input_vars)
            if "{NAME}" in call:
                expr = call.replace("{NAME}", _pyid(n))
                lines.append(f"        {out_var} = {expr}")
            elif len(input_vars) != 1:
                args = ", ".join(input_vars)
                lines.append(f"        {out_var} = self.{_pyid(n)}({args})")
            else:
                lines.append(
                    f"        {out_var} = self.{_pyid(n)}({input_vars[0]})"
                )
        else:
            if ly.op.name == "Reshape":
                shape_args = ", ".join(ly.op.args)
                expr = f"torch.reshape({input_vars[0]}, ({shape_args},))"
            else:
                expr = spec.pytorch_call(ly.op.args, input_vars)
            lines.append(f"        {out_var} = {expr}")

        var[n] = out_var
        has_body = True

    out_vars = [var.get(o.name, _pyid(o.name)) for o in arch.outputs()]
    if len(out_vars) == 1:
        lines.append(f"        return {out_vars[0]}")
    else:
        lines.append(f"        return {', '.join(out_vars)}")

    if not has_body and not out_vars:
        lines.append("        pass")

    lines.append("")
    return "\n".join(lines)


def _class_name(name: str) -> str:
    parts = name.replace("-", "_").split("_")
    return "".join(p[:1].upper() + p[1:] if p else "" for p in parts) or "Model"


def _pyid(name: str) -> str:
    out = []
    for c in name:
        if c.isalnum() or c == "_":
            out.append(c)
        else:
            out.append("_")
    s = "".join(out)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def _default_literal(hp) -> str | None:
    if hp.default is None:
        return None
    return repr(hp.default)
